[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"
default-run = "aoc2024"

[dependencies]
ahash = "0.8"
bit-vec = "0.8"
crossterm = "0.28"
glam = "0.29"
smallvec = "1.13"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
